### ISSUE TITLE
when I run the command 'blender ......',I got this

### ISSUE THREAD

**Issue by Pean-Mura** [PeizhuoLi/neural-blend-shapes#2]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\360Downloads\neural_blend_shapes_main\blender_scripts\render_mesh.py", line 96, in <module>
    batch_render(args.obj_path)
  File "D:\360Downloads\neural_blend_shapes_main\blender_scripts\render_mesh.py", line 56, in batch_render
    render_obj(os.path.join(dir, file))
  File "D:\360Downloads\neural_blend_shapes_main\blender_scripts\render_mesh.py", line 33, in render_obj
    add_material_for_objs([obj], 'character')
  File "D:\360Downloads\neural_blend_shapes_main\blender_scripts\render_mesh.py", line 28, in add_material_for_objs
    raise Exception("This line shouldn't be reached")
Exception: This line shouldn't be reached

I don't know why this happen.
My command is ' blender -P render_mesh.py -b'

**Comment by PeizhuoLi** [comment]
Hi, this part of the code is used to add material to the generated mesh, where the material is stored in the blend file. You may discard this part, or please follow the readme and run `blender ../eval_constant/simple_scene.blend -P render_mesh.py -b`.
